### ISSUE TITLE
Warning: Error in pngfun: invalid quartz() device size

### ISSUE THREAD

**Issue by ghost** [JGCRI/GCAM-LAC-dashboard#18]
Hi!

The following errors pop up when running the gcamlacdash package on  RStudio. I'm running it on a Mac. Any insight into what may be causing it would be deeply appreciated. 

**Warning: Error in pngfun: invalid quartz() device size**
  128: pngfun
  127: startPNG
  126: drawPlot
  112: <reactive:plotObj>
   96: drawReactive
   83: origRenderFunc
   82: output$dashboard-Water-Scarcity-plot
    2: shiny::runApp
    1: gcamlacdash::run

**Warning: Error in pngfun: invalid quartz() device size**
  128: pngfun
  127: startPNG
  126: drawPlot
  112: <reactive:plotObj>
   96: drawReactive
   83: origRenderFunc
   82: output$dashboard-Water-Supply-plot
    2: shiny::runApp
    1: gcamlacdash::run

**Warning: Error in pngfun: invalid quartz() device size**
  128: pngfun
  127: startPNG
  126: drawPlot
  112: <reactive:plotObj>
   96: drawReactive
   83: origRenderFunc
   82: output$dashboard-Water-Demand-plot
    2: shiny::runApp
    1: gcamlacdash::run

**Comment by rplzzz** [comment]
Hmm.  I've never seen that error before.  It looks like it has something to do with the graphics device configuration.  I'll keep digging to see what I can come up with.

**Comment by rplzzz** [comment]
Are you able to run any of the basic examples using the `shiny` package?  Take this one for example:

https://github.com/rstudio/shiny-examples/tree/master/050-kmeans-example

If you download the code and run it, do you get the same error?

**Comment by ghost** [comment]
Thank you for the quick reply. Yes I am able to run the examples smoothly without any error showing up.

**Comment by Winode** [comment]
Hello! Are you using renderPlot() when you should be using renderTable() ? I just fixed the same issue you are having by making this simple adjustment.

**Comment by rplzzz** [comment]
@Winode Thanks for the tip.  I looked through the code, and all of the calls to `renderPlot()` seem to be displaying bona-fide plots, so I don't think that's the problem.  Also, the developer and several other users have been using it without encountering this problem.

@VictorSindato I'm going to take another run at reproducing the bug toward the end of next week.  Thanks for your patience.

**Comment by TadaoHashimoto** [comment]
I guess you use unmatched function(render*() or *Output()).
please check your code.

**Comment by cypressf** [comment]
I'm also encountering this issue. @rplzzz have you had a chance to look into the bug? Out of curiosity, when you run it successfully, what version of R are you running, and what OS?


macOS 10.14.6 (18G2022)

R installed via `brew cask install r` https://formulae.brew.sh/cask/rstudio

R version 3.6.1 (2019-07-05) Platform: x86_64-apple-darwin15.6.0 (64-bit)
RStudio Version 1.2.5019
"Elderflower" (fba733f0, 2019-10-24)
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.1 Chrome/69.0.3497.128 Safari/537.36

**Comment by cypressf** [comment]
I uninstalled the homebrew R installation with `brew cask uninstall r` and then reinstalled R using the disk images on https://rstudio.com/products/rstudio/download/#download and I still have the same error.

R version 3.6.2 (2019-12-12) Platform: x86_64-apple-darwin15.6.0 (64-bit)
RStudio Version 1.2.5033
"Orange Blossom" (330255dd, 2019-12-03)
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.1 Chrome/69.0.3497.128 Safari/537.36

**Comment by rplzzz** [comment]
Ah, sorry, you guys.  I never got back around to investigating this.  I'm actually not working on this project anymore, but I'm going to tag @crvernon, who is now in charge of such things.

**Comment by cypressf** [comment]
Out of curiosity, I tried to get this to run in Ubuntu 18 and encountered a different, but similar looking error:


```
Warning: Error in pngfun: invalid 'width' argument
  128: pngfun
  127: startPNG
  126: drawPlot
  112: <reactive:plotObj>
   96: drawReactive
   83: origRenderFunc
   82: output$dashboard-Water-Scarcity-plot
    2: shiny::runApp
    1: gcamlacdash::run
Warning: Error in pngfun: invalid 'width' argument
  128: pngfun
  127: startPNG
  126: drawPlot
  112: <reactive:plotObj>
   96: drawReactive
   83: origRenderFunc
   82: output$dashboard-Water-Supply-plot
    2: shiny::runApp
    1: gcamlacdash::run
Warning: Error in pngfun: invalid 'width' argument
  128: pngfun
  127: startPNG
  126: drawPlot
  112: <reactive:plotObj>
   96: drawReactive
   83: origRenderFunc
   82: output$dashboard-Water-Demand-plot
    2: shiny::runApp
    1: gcamlacdash::run
```

**Comment by cypressf** [comment]
@calebbraun I noticed you were poking around on a branch branch to troubleshoot this. I checked out [your branch](https://github.com/JGCRI/GCAM-LAC-dashboard/commit/b161fe6cb1437df5363b5cf21518cc097fa10edb#diff-ce47db0e300eba527b0ce30c69e07c48R133), and it fixed the issue for me.

Is there anything preventing that from being merged to the main branch? Anything I could do to help?

**Comment by sanjmeh** [comment]
Any progess on this thread?

**Comment by zarrarkhan** [comment]
> Any progess on this thread?

@sanjmeh, GCAM-LAC-dashboard is not in active development anymore. We are migrating to a new dashboard "Argus" which will be released in the coming weeks (we are still cleaning up bugs and the code). Argus is a more generic dashboard for use with gcam and other input data formats. You can get a preview (not all parts are functioning) of Argus here:
- https://jgcri.shinyapps.io/argus/
- https://github.com/JGCRI/argus 

For now you can just see the kinds of visualizations Argus will provide using the default data. Once it is officially released you will be able to upload GCAM databases and several other formats. 

Can you please, let us know a bit more about what you are trying to do with GCAM-LAC-dashboard and if you think Argus will meet your needs?

Thanks!
